---
- hosts:
  - all
  remote_user: root
  gather_facts: no
  vars:
    ansible_ssh_private_key_file: ../secrets/id_rsa
  tasks:
  - name: Wait for hosts to become reachable
    wait_for_connection:
      timeout: 600

- hosts:
  - all
  remote_user: root
  vars:
    ansible_ssh_private_key_file: ../secrets/id_rsa

  tasks:
  - name: Install several packages
    package:
      name: ['htop', 'nano']
      state: present

  roles:
  - yum-cron
  - opennebula
